version: '3'

services:
  volumerize:
    depends_on:
      - jenkins
    # image: blacklabelops/volumerize
    build: .
    container_name: volumerize
    volumes:
      - jenkins_volume:/source:ro
      - backup_volume:/backup
      - cache_volume:/volumerize-cache
    environment:
      - 'VOLUMERIZE_SOURCE=/source'
      - 'VOLUMERIZE_TARGET=mega://email:password@mega.nz/'
      - 'VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run'

  jenkins:
    image: blacklabelops/jenkins
    container_name: jenkins
    volumes:
      - jenkins_volume:/jenkins
    ports:
      - '80:8080'

volumes:
  jenkins_volume:
    external: false
  backup_volume:
    external: false
  cache_volume:
    external: false
